services:
  web:
    build:
      context: .
      dockerfile: infrastructure/web/Dockerfile
    entrypoint: php artisan octane:frankenphp --max-requests=1
    ports:
      - "8089:8000"
    volumes:
      - .:/app
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8088:8080